#! /bin/bash

export LANG=sv_SE.utf8
export LC_MESSAGES=C

# shellcheck source=../.functions
[[ -r ~/.functions && ! "$os" ]] && . ~/.functions
[[ $os = Da ]] && exec quartz-wm

# Faster repeat rate (default is 660 25)
xset r rate 500 50

# Disable repeat on character keys
for keysym in {10..21} {79..89} {24..61}; do
  xset -r $keysym
done

# Enable repeat for cursor movement and space
for keysym in 22 113 114 111 116 65; do
  xset r $keysym
done

host=$(hostname -s)
case $host in
    vdx*)
        export LD_PRELOAD=/usr/lib64/libctxXrandrhook.so
        ;;
    lxa*)
        export LIBGL_ALWAYS_INDIRECT=1
        ;;
esac
exec >"$HOME"/.xsessionlog 2>"$HOME"/.xsessionlog

# shellcheck source=../.bash_profile
test -r "$HOME"/.bash_profile && . "$HOME"/.bash_profile

xset b off
xrdb -load "$HOME"/.Xresources

case $host in
    jane)
        nice -n 5 xmm -usedcolor "#009900" -activecolor "#0000ff" -inactivecolor "#00cc99" -freecolor "#ffffcc" -swapcolor red -nolabel -jumpscroll 10 -geometry 520x310-1602+2 &
        xmodmap ~/X11/xmodmap/pc
        xmodmap ~/X11/xmodmap/pc_kp
        xmodmap -e 'keycode 108 = Mode_switch'
        # For some uknown reason xscreensaver doesn't set dpms settings from
        # .xscreensaver at startup
        xset dpms 6000 6600 7200
        ;;
    bean)
        xmodmap ~/X11/xmodmap/macbook
        xmodmap -e 'keycode 108 = Mode_switch'
        ;;
    v10073)
        xmodmap ~/X11/xmodmap/pc
        xmodmap ~/X11/xmodmap/x-win32_kp
        xmodmap -e 'keycode 113 = Mode_switch'
        ;;
    *)
        xmodmap ~/X11/xmodmap/pc
        xmodmap ~/X11/xmodmap/pc_kp
        xmodmap -e 'keycode 113 = Mode_switch'
        ;;
esac

if hash -r xsetbg > /dev/null 2>&1 && [[ -f $HOME/X11/rainlight.gif ]]; then
    # Let fvwm set the bg image
    :
else
    xsetroot -solid "#703000"
fi

HOST=$host fvwm

# Cleanup some processes that tend to be left after exiting, and that might
# keep ssh X11 tunnel open preventing ssh from exiting
killall -u jjri -r -- dbus- -agent emacs

# And kill all remaining X clients
xlsclients -al | awk '/^Window /{print $NF}' | sed -e 's/:$//' | while read -r id; do
    xkill -id "$id"
done
