#! /bin/sh
host=$(hostname -s)
case $host in
    vdx*)
	export LD_PRELOAD=/usr/lib64/libctxXrandrhook.so
	;;
esac
exec >$HOME/.xsessionlog 2>$HOME/.xsessionlog

test -r $HOME/.bash_profile && . $HOME/.bash_profile

xset b off
xrdb -load $HOME/.Xdefaults

case $host in
    jane)
	xmodmap ~/X11/xmodmap/pc
	xmodmap -e 'keycode 108 = Mode_switch'
	;;
    bean)
	xmodmap ~/X11/xmodmap/macbook
	xmodmap -e 'keycode 108 = Mode_switch'
	;;
    *)
	xmodmap ~/X11/xmodmap/pc
	xmodmap -e 'keycode 113 = Mode_switch'
	;;
esac

if $(hash -r xsetbg > /dev/null 2>&1) && [[ -f $HOME/X11/rainlight.gif ]]; then
    # Let fvwm set the bg image
    :
else
    xsetroot -solid "#703000"
fi

fvwm
