#! /bin/sh

export LANG=sv_SE.utf8
export LC_MESSAGES=C

[ -r ~/.functions -a ! "$os" ] && . ~/.functions
[ $os = Da ] && exec quartz-wm

host=$(hostname -s)
case $host in
    vdx*)
        export LD_PRELOAD=/usr/lib64/libctxXrandrhook.so
        ;;
esac
exec >$HOME/.xsessionlog 2>$HOME/.xsessionlog

test -r $HOME/.bash_profile && . $HOME/.bash_profile

xset b off
xrdb -load $HOME/.Xdefaults

case $host in
    jane)
        nice -n 5 xmm -usedcolor "#009900" -activecolor "#0000ff" -inactivecolor "#00cc99" -freecolor "#ffffcc" -swapcolor red -nolabel -jumpscroll 10 -geometry 520x310-1602+2 &
        xmodmap ~/X11/xmodmap/pc
        xmodmap ~/X11/xmodmap/pc_kp
        xmodmap -e 'keycode 108 = Mode_switch'
        ;;
    bean)
        xmodmap ~/X11/xmodmap/macbook
        xmodmap -e 'keycode 108 = Mode_switch'
        ;;
    v10073)
        xmodmap ~/X11/xmodmap/pc
        xmodmap ~/X11/xmodmap/x-win32_kp
        xmodmap -e 'keycode 113 = Mode_switch'
        ;;
    *)
        xmodmap ~/X11/xmodmap/pc
        xmodmap ~/X11/xmodmap/pc_kp
        xmodmap -e 'keycode 113 = Mode_switch'
        ;;
esac

if $(hash -r xsetbg > /dev/null 2>&1) && [[ -f $HOME/X11/rainlight.gif ]]; then
    # Let fvwm set the bg image
    :
else
    xsetroot -solid "#703000"
fi

HOST=$host fvwm

# Cleanup some processes that tend to be left after exiting, and that might
# keep ssh X11 tunnel open preventing ssh from exiting
killall -u jjri -r -- dbus- -agent emacs

# And kill all remaining X clients
xlsclients -al | awk '/^Window /{print $NF}' | sed -e 's/:$//' | while read id; do
    xkill -id $id
done
