;; Exchange bindings for "RETURN" and "LINEFEED" to support indentation.
(define-key global-map "\C-j" 'newline)
(define-key global-map "\C-m" 'reindent-then-newline-and-indent)

;(define-key global-map " " 'insert-or-scroll)
(define-key global-map "\C-x\C-o" 'bury-buffer)
(define-key global-map "\C-m" 'newline-and-indent)
(define-key global-map "\C-d" 'delete-char-or-list)
(define-key global-map "\C-u" 'delete-line)
;(define-key global-map "\C-z" 'save-buffers-suspend)
(define-key global-map "\C-cw" 'append-signature-long)
(define-key global-map "\C-c\C-w" 'append-signature-short)
(define-key global-map "\M-g" 'goto-line)
(define-key global-map "\C-ci" 'isearch-toggle-case-fold)

(define-key text-mode-map "\e\t" 'lisp-complete-symbol)

(cond ((fboundp 'magit-status)
       (define-key global-map "\C-xvv" 'magit-status)))
(cond ((>= emacs-major-version 21)
       (define-key global-map [home] 'beginning-of-buffer)
       (define-key global-map [end] 'end-of-buffer)
       ))

(cond ((getenv "PUTTY")
       (define-key global-map [find] 'beginning-of-buffer)
       (define-key global-map [select] 'end-of-buffer)
       (define-key global-map [kp-0] "0")
       (define-key global-map [kp-1] "1")
       (define-key global-map [kp-2] "2")
       (define-key global-map [kp-3] "3")
       (define-key global-map [kp-4] "4")
       (define-key global-map [kp-5] "5")
       (define-key global-map [kp-6] "6")
       (define-key global-map [kp-7] "7")
       (define-key global-map [kp-8] "8")
       (define-key global-map [kp-9] "9")
       (define-key global-map [kp-divide] "/")
       (define-key global-map [kp-multiply] "*")
       (define-key global-map [kp-subtract] "-")
       (define-key global-map [kp-add] "+")
       (define-key global-map [kp-enter] 'newline)
       (define-key global-map "On" ",")
       ))
